// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * title field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * link field in *Contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Home → Contact button*
 */
export interface HomeDocumentDataContactButtonItem {
  /**
   * Label field in *Home → Contact button*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.contact_button[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Home → Contact button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.contact_button[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type HomeDocumentDataSlicesSlice =
  | ReasonSlice
  | FooterSlice
  | V03Slice
  | V04Slice
  | V01Slice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Parent field in *Home*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"home">;

  /**
   * Contact button field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.contact_button[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_button: prismic.GroupField<
    Simplify<HomeDocumentDataContactButtonItem>
  >;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Nav Footer → Links*
 */
export interface NavForBusinessDocumentDataLinksItem {
  /**
   * Label field in *Nav Footer → Links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_for_business.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Nav Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_for_business.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Nav Footer documents
 */
interface NavForBusinessDocumentData {
  /**
   * Title field in *Nav Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_for_business.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Links field in *Nav Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_for_business.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavForBusinessDocumentDataLinksItem>>;
}

/**
 * Nav Footer document from Prismic
 *
 * - **API ID**: `nav_for_business`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavForBusinessDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavForBusinessDocumentData>,
    "nav_for_business",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ContactDocument
  | HomeDocument
  | NavForBusinessDocument
  | NavigationDocument
  | SettingsDocument;

/**
 * Primary content in *Footer → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Text field in *Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Copyright base field in *Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Copyright base
   * - **API ID Path**: footer.primary.copyright
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField;

  /**
   * Copyright logo field in *Footer → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.primary.copyright_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  copyright_logo: prismic.ImageField<never>;

  /**
   * Footer Logo field in *Footer → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.primary.footer_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Reason → Primary*
 */
export interface ReasonSliceDefaultPrimary {
  /**
   * Image field in *Reason → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reason.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Reason Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReasonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReasonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Reason*
 */
type ReasonSliceVariation = ReasonSliceDefault;

/**
 * Reason Shared Slice
 *
 * - **API ID**: `reason`
 * - **Description**: Reason
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReasonSlice = prismic.SharedSlice<"reason", ReasonSliceVariation>;

/**
 * Primary content in *V01 → Primary*
 */
export interface V01SliceDefaultPrimary {
  /**
   * Title field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title of the block
   * - **API ID Path**: v01.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Key 1 field in *V01 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.key_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  key_1: prismic.KeyTextField;

  /**
   * Description field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: v01.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Key 2 field in *V01 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.key_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  key_2: prismic.KeyTextField;

  /**
   * Points field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.points
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  points: prismic.RichTextField;

  /**
   * Page Number field in *V01 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Block Number
   * - **API ID Path**: v01.primary.page_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_number: prismic.KeyTextField;

  /**
   * Picture field in *V01 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Button Text field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Button text
   * - **API ID Path**: v01.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_text: prismic.RichTextField;

  /**
   * Button Link field in *V01 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Background field in *V01 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Background color
   * - **Default Value**: White
   * - **API ID Path**: v01.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"White" | "Grey", "filled">;
}

/**
 * Primary content in *V01 → Items*
 */
export interface V01SliceDefaultItem {
  /**
   * Key 1 field in *V01 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.items[].key_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  key_1: prismic.RichTextField;

  /**
   * Value 1 field in *V01 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.items[].value_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  value_1: prismic.RichTextField;
}

/**
 * Default variation for V01 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type V01SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<V01SliceDefaultPrimary>,
  Simplify<V01SliceDefaultItem>
>;

/**
 * Primary content in *V01 → Primary*
 */
export interface V01SliceImageLeftPrimary {
  /**
   * Title field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title of the block
   * - **API ID Path**: v01.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Key 1 field in *V01 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.key_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  key_1: prismic.KeyTextField;

  /**
   * Description field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: v01.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Key 2 field in *V01 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.key_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  key_2: prismic.KeyTextField;

  /**
   * Points field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.points
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  points: prismic.RichTextField;

  /**
   * Page Number field in *V01 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Block Number
   * - **API ID Path**: v01.primary.page_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_number: prismic.KeyTextField;

  /**
   * Picture field in *V01 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Button Text field in *V01 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Button text
   * - **API ID Path**: v01.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_text: prismic.RichTextField;

  /**
   * Button Link field in *V01 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Background field in *V01 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Background color
   * - **Default Value**: White
   * - **API ID Path**: v01.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"White" | "Grey", "filled">;
}

/**
 * Primary content in *V01 → Items*
 */
export interface V01SliceImageLeftItem {
  /**
   * Key 1 field in *V01 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.items[].key_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  key_1: prismic.RichTextField;

  /**
   * Value 1 field in *V01 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v01.items[].value_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  value_1: prismic.RichTextField;
}

/**
 * Image left variation for V01 Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type V01SliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<V01SliceImageLeftPrimary>,
  Simplify<V01SliceImageLeftItem>
>;

/**
 * Slice variation for *V01*
 */
type V01SliceVariation = V01SliceDefault | V01SliceImageLeft;

/**
 * V01 Shared Slice
 *
 * - **API ID**: `v01`
 * - **Description**: V01
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type V01Slice = prismic.SharedSlice<"v01", V01SliceVariation>;

/**
 * Primary content in *V03 → Primary*
 */
export interface V03SliceDefaultPrimary {
  /**
   * Page number field in *V03 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v03.primary.page_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_number: prismic.KeyTextField;

  /**
   * Points field in *V03 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Points
   * - **API ID Path**: v03.primary.points
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  points: prismic.RichTextField;

  /**
   * Block name field in *V03 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v03.primary.block_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  block_name: prismic.RichTextField;
}

/**
 * Primary content in *V03 → Items*
 */
export interface V03SliceDefaultItem {
  /**
   * Message field in *V03 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v03.items[].message
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  message: prismic.RichTextField;

  /**
   * User Name field in *V03 → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v03.items[].user_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  user_name: prismic.KeyTextField;

  /**
   * User Title field in *V03 → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v03.items[].user_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  user_title: prismic.KeyTextField;

  /**
   * Avatar field in *V03 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: v03.items[].avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;
}

/**
 * Default variation for V03 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type V03SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<V03SliceDefaultPrimary>,
  Simplify<V03SliceDefaultItem>
>;

/**
 * Slice variation for *V03*
 */
type V03SliceVariation = V03SliceDefault;

/**
 * V03 Shared Slice
 *
 * - **API ID**: `v03`
 * - **Description**: V03
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type V03Slice = prismic.SharedSlice<"v03", V03SliceVariation>;

/**
 * Primary content in *V04 → Primary*
 */
export interface V04SliceDefaultPrimary {
  /**
   * Block Number field in *V04 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v04.primary.block_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  block_number: prismic.KeyTextField;

  /**
   * Title field in *V04 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v04.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *V04 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: v04.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Button field in *V04 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v04.primary.button
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button: prismic.RichTextField;

  /**
   * Question field in *V04 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: v04.primary.question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;
}

/**
 * Primary content in *V04 → Items*
 */
export interface V04SliceDefaultItem {
  /**
   * Picture field in *V04 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: v04.items[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Picture Position field in *V04 → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose picture position
   * - **Default Value**: Top Left
   * - **API ID Path**: v04.items[].picture_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  picture_position: prismic.SelectField<
    "Top Left" | "Top Rigth" | "Bottom Right" | "Bottom Left",
    "filled"
  >;
}

/**
 * Default variation for V04 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type V04SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<V04SliceDefaultPrimary>,
  Simplify<V04SliceDefaultItem>
>;

/**
 * Slice variation for *V04*
 */
type V04SliceVariation = V04SliceDefault;

/**
 * V04 Shared Slice
 *
 * - **API ID**: `v04`
 * - **Description**: V04
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type V04Slice = prismic.SharedSlice<"v04", V04SliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataContactButtonItem,
      HomeDocumentDataSlicesSlice,
      NavForBusinessDocument,
      NavForBusinessDocumentData,
      NavForBusinessDocumentDataLinksItem,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      ReasonSlice,
      ReasonSliceDefaultPrimary,
      ReasonSliceVariation,
      ReasonSliceDefault,
      V01Slice,
      V01SliceDefaultPrimary,
      V01SliceDefaultItem,
      V01SliceImageLeftPrimary,
      V01SliceImageLeftItem,
      V01SliceVariation,
      V01SliceDefault,
      V01SliceImageLeft,
      V03Slice,
      V03SliceDefaultPrimary,
      V03SliceDefaultItem,
      V03SliceVariation,
      V03SliceDefault,
      V04Slice,
      V04SliceDefaultPrimary,
      V04SliceDefaultItem,
      V04SliceVariation,
      V04SliceDefault,
    };
  }
}
