// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer: dynamic(() => import("./Footer")),
  reason: dynamic(() => import("./Reason")),
  v01: dynamic(() => import("./V01")),
  v03: dynamic(() => import("./V03")),
  v04: dynamic(() => import("./V04")),
};
